[#ftl output_format="HTML"]
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Blank_Template</title></head>
<body><form method="post" id="iodv"><div><label id="imfj">usrname</label><input type="text" id="inu8a"></div><div id="inke8">password</div><input type="text" id="i93z3"><div><button type="button">Send</button></div></form></body>


</html>